// Generated by CoffeeScript 1.6.2
(function() {
  window.describe("Block Class", function() {
    var block;

    block = null;
    beforeEach(function() {
      return block = new Tetris.Block(10);
    });
    it("should be different from null", function() {
      return expect(block).not.toEqual(null);
    });
    return describe("Constructor default values", function() {
      it("should have size 10", function() {
        return expect(block.size).toEqual(10);
      });
      it("should not be moving", function() {
        return expect(block.moving).toBeFalsy();
      });
      it("should have a cube shape", function() {
        return expect(block.cube).toBeDefined();
      });
      return it("should be in the center", function() {
        expect(block.cube.position.x).toEqual(0);
        expect(block.cube.position.y).toEqual(0);
        return expect(block.cube.position.z).toEqual(0);
      });
    });
  });

}).call(this);
