// Generated by CoffeeScript 1.6.2
(function() {
  window.describe("Block Class", function() {
    return describe("isInsideBox function", function() {
      return it("should have shape null", function() {
        return expect(shape).toBeNull();
      });
    });
  });

}).call(this);
