// Generated by CoffeeScript 1.6.2
(function() {
  window.Tetris = {};

  Tetris.Block = (function() {
    function Block(x, y, z) {
      this.x = x;
      this.y = y;
      this.z = z;
      this.color = 0xFF0000;
      this.active = false;
      this.cube = null;
    }

    Block.prototype.setColor = function(color) {
      return this.color = color;
    };

    Block.prototype.draw = function() {
      this.active = true;
      this.cube = new THREE.SceneUtils.createMultiMaterialObject(new THREE.CubeGeometry(BLOCK_SIZE, BLOCK_SIZE, BLOCK_SIZE), [
        new THREE.MeshBasicMaterial({
          color: 0xFFAA00,
          wireframe: true,
          transparent: true
        }), new THREE.MeshBasicMaterial({
          color: this.color
        })
      ]);
      this.calculate_pos();
      return scene.add(this.cube);
    };

    Block.prototype.print = function() {
      return console.log(this.cube.position.x + ", " + this.cube.position.y + ", " + this.cube.position.z);
    };

    Block.prototype.calculate_pos = function() {
      this.cube.position.x = (TABLE_WIDTH / 2 + (this.x - (TABLE_WIDTH - 0.5))) * BLOCK_SIZE;
      this.cube.position.y = -(TABLE_HEIGHT / 2 + (this.y - (TABLE_HEIGHT - 0.5))) * BLOCK_SIZE;
      return this.cube.position.z = (this.z - TABLE_DEPTH / 2 + 0.5) * BLOCK_SIZE;
    };

    Block.prototype.erase = function() {
      this.active = false;
      return scene.remove(this.cube);
    };

    return Block;

  })();

}).call(this);
