// Generated by CoffeeScript 1.6.2
(function() {
  var ASPECT, BLOCK_SIZE, DEPTH, FAR, HEIGHT, NEAR, TABLE_DEPTH, TABLE_HEIGHT, TABLE_WIDTH, VIEW_ANGLE, WIDTH, boundingBox, camera, canvas, render, renderer, scene;

  BLOCK_SIZE = 100;

  TABLE_WIDTH = 7;

  TABLE_HEIGHT = 7;

  TABLE_DEPTH = 15;

  WIDTH = BLOCK_SIZE * TABLE_WIDTH;

  HEIGHT = BLOCK_SIZE * TABLE_HEIGHT;

  DEPTH = BLOCK_SIZE * TABLE_DEPTH;

  VIEW_ANGLE = 45;

  ASPECT = WIDTH / HEIGHT;

  NEAR = 0.1;

  FAR = 10000;

  scene = new THREE.Scene();

  camera = new THREE.PerspectiveCamera(VIEW_ANGLE, ASPECT, NEAR, FAR);

  renderer = new THREE.WebGLRenderer();

  renderer.setSize(WIDTH, HEIGHT);

  canvas = $('#canvas');

  canvas.append(renderer.domElement);

  boundingBox = new THREE.Mesh(new THREE.CubeGeometry(WIDTH, HEIGHT, DEPTH * 2, TABLE_WIDTH, TABLE_HEIGHT, TABLE_DEPTH * 2), new THREE.MeshBasicMaterial({
    color: 0x999999,
    wireframe: true,
    wireframeLinewidth: 2
  }));

  scene.add(boundingBox);

  camera.position.z = DEPTH - 54 - BLOCK_SIZE * 6;

  render = function() {
    requestAnimationFrame(render);
    return renderer.render(scene, camera);
  };

  render();

}).call(this);
