// Generated by CoffeeScript 1.4.0
(function() {
  var canvas, context;

  canvas = document.getElementById("game");

  context = canvas.getContext("2d");

  canvas.width = 800;

  canvas.height = 600;

}).call(this);
