// Generated by CoffeeScript 1.6.2
(function() {
  window.Canon = (function() {
    function Canon(x, y, imgObj, layer) {
      var animations;

      this.x = x;
      this.y = y;
      this.imgObj = imgObj;
      this.layer = layer;
      this.velocity = 15;
      animations = {
        canon: [
          {
            x: 3,
            y: 111,
            width: 45,
            heigth: 24
          }
        ]
      };
      this.sprite = new Kinetic.Sprite({
        x: this.x,
        y: this.y,
        image: this.imgObj,
        animation: 'canon',
        animations: animations,
        frameRate: 7,
        index: 0
      });
      this.layer.add(this.sprite);
    }

    return Canon;

  })();

}).call(this);
