// Generated by CoffeeScript 1.6.2
(function() {
  var BLOCK_SIZE, BORDER, HEIGHT, HEIGHT_BLOCKS, WIDTH, WIDTH_BLOCKS, alienMovPause, alienStrArr, aliensArr, aliensDirection, aliensDownMove, aliensLayer, aliensSideMove, aliensWidthArr, animateAliens, animations, background, backgroundLayer, bullet_vel, bulletsAnimation, bulletsArr, canon, canon_vel, checkAliensGoDown, checkBulletsOut, explosionAnim, imageObj, moveAliens, moveCanon, removeAlien, removeBullet, shootBullet, stage;

  BLOCK_SIZE = 3;

  WIDTH_BLOCKS = 184;

  HEIGHT_BLOCKS = 191;

  WIDTH = WIDTH_BLOCKS * BLOCK_SIZE;

  HEIGHT = HEIGHT_BLOCKS * BLOCK_SIZE;

  BORDER = 4 * BLOCK_SIZE;

  canon = null;

  aliensArr = [];

  bulletsArr = [];

  canon_vel = 15;

  bullet_vel = 5;

  aliensDirection = 1;

  alienMovPause = 500;

  aliensSideMove = 2 * BLOCK_SIZE;

  aliensDownMove = 6 * BLOCK_SIZE;

  alienStrArr = ['alien03', 'alien02', 'alien02', 'alien01', 'alien01'];

  aliensWidthArr = [8 * BLOCK_SIZE, 11 * BLOCK_SIZE, 11 * BLOCK_SIZE, 12 * BLOCK_SIZE, 12 * BLOCK_SIZE];

  stage = new Kinetic.Stage({
    container: "container",
    width: WIDTH,
    height: HEIGHT
  });

  backgroundLayer = new Kinetic.Layer;

  aliensLayer = new Kinetic.Layer;

  animations = {
    alien01: [
      {
        x: BLOCK_SIZE,
        y: BLOCK_SIZE,
        width: 12 * BLOCK_SIZE,
        height: 8 * BLOCK_SIZE
      }, {
        x: 14 * BLOCK_SIZE,
        y: BLOCK_SIZE,
        width: 12 * BLOCK_SIZE,
        height: 8 * BLOCK_SIZE
      }
    ],
    alien02: [
      {
        x: BLOCK_SIZE,
        y: 10 * BLOCK_SIZE,
        width: 11 * BLOCK_SIZE,
        height: 8 * BLOCK_SIZE
      }, {
        x: 13 * BLOCK_SIZE,
        y: 10 * BLOCK_SIZE,
        width: 11 * BLOCK_SIZE,
        height: 8 * BLOCK_SIZE
      }
    ],
    alien03: [
      {
        x: BLOCK_SIZE,
        y: 19 * BLOCK_SIZE,
        width: 8 * BLOCK_SIZE,
        height: 8 * BLOCK_SIZE
      }, {
        x: 10 * BLOCK_SIZE,
        y: 19 * BLOCK_SIZE,
        width: 8 * BLOCK_SIZE,
        height: 8 * BLOCK_SIZE
      }
    ],
    spaceship: [
      {
        x: BLOCK_SIZE,
        y: (3 * 8 + 4) * BLOCK_SIZE,
        width: 16 * BLOCK_SIZE,
        height: 8 * BLOCK_SIZE
      }
    ],
    canon: [
      {
        x: BLOCK_SIZE,
        y: (4 * 8 + 5) * BLOCK_SIZE,
        width: 15 * BLOCK_SIZE,
        height: 8 * BLOCK_SIZE
      }
    ]
  };

  explosionAnim = {
    idle: [
      {
        x: 0,
        y: 0,
        width: 0,
        height: 0
      }
    ],
    explosion: [
      {
        x: 5,
        y: 3,
        width: 32,
        height: 33
      }, {
        x: 42,
        y: 3,
        width: 30,
        height: 33
      }, {
        x: 79,
        y: 3,
        width: 33,
        height: 33
      }, {
        x: 121,
        y: 3,
        width: 33,
        height: 33
      }
    ]
  };

  background = new Kinetic.Rect({
    x: 0,
    y: 0,
    width: WIDTH,
    height: HEIGHT,
    fill: "#000000"
  });

  backgroundLayer.add(background);

  stage.add(backgroundLayer);

  imageObj = new Image();

  imageObj.src = "images/aliens_all.png";

  imageObj.onload = function() {
    var new_alien, num1, num2, _i, _j;

    canon = new Kinetic.Sprite({
      x: WIDTH / 2 - 7 * BLOCK_SIZE,
      y: HEIGHT - (8 * BLOCK_SIZE + BORDER),
      image: imageObj,
      animation: 'canon',
      animations: animations,
      frameRate: 1,
      width: 15 * BLOCK_SIZE,
      height: 8 * BLOCK_SIZE
    });
    aliensLayer.add(canon);
    stage.add(aliensLayer);
    canon.start();
    for (num1 = _i = 0; _i <= 4; num1 = ++_i) {
      for (num2 = _j = 0; _j <= 10; num2 = ++_j) {
        new_alien = new Kinetic.Sprite({
          x: num2 * (12 + 2) * BLOCK_SIZE,
          y: num1 * (8 + 6) * BLOCK_SIZE,
          image: imageObj,
          animation: alienStrArr[num1],
          animations: animations,
          frameRate: 2,
          width: aliensWidthArr[num1],
          height: 8 * BLOCK_SIZE
        });
        aliensLayer.add(new_alien);
        new_alien.start();
        aliensArr.push(new_alien);
      }
    }
    return moveAliens(BORDER, BORDER);
  };

  document.onkeydown = function(event) {
    switch (event.keyCode) {
      case 37:
      case 65:
        moveCanon(-1);
        break;
      case 39:
      case 68:
        moveCanon(1);
        break;
      case 32:
        shootBullet();
    }
    return event.preventDefault();
  };

  moveCanon = function(direction) {
    var next_pos, speed;

    speed = direction * canon_vel;
    next_pos = canon.getX() + speed;
    if (next_pos > BORDER && next_pos < (WIDTH - (15 * BLOCK_SIZE + BORDER))) {
      return canon.move(speed, 0);
    }
  };

  shootBullet = function() {
    var bullet;

    bullet = new Kinetic.Rect({
      x: canon.getX() + canon.getWidth() / 2 - 1,
      y: canon.getY() - canon.getHeight() / 2,
      width: BLOCK_SIZE,
      height: 4 * BLOCK_SIZE,
      fill: "#FFCCCC"
    });
    aliensLayer.add(bullet);
    return bulletsArr.push(bullet);
  };

  checkBulletsOut = function() {
    var bullet, _i, _len, _results;

    _results = [];
    for (_i = 0, _len = bulletsArr.length; _i < _len; _i++) {
      bullet = bulletsArr[_i];
      if (bullet && bullet.getY() < 0) {
        _results.push(removeBullet(bullet));
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  removeBullet = function(bullet) {
    var index;

    if (bullet) {
      index = bulletsArr.indexOf(bullet);
      bullet.destroy();
      return bulletsArr.splice(index, 1);
    }
  };

  bulletsAnimation = new Kinetic.Animation(function(frame) {
    var bullet, _i, _len, _results;

    checkBulletsOut();
    _results = [];
    for (_i = 0, _len = bulletsArr.length; _i < _len; _i++) {
      bullet = bulletsArr[_i];
      if (bullet) {
        _results.push(bullet.move(0, -bullet_vel));
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  });

  bulletsAnimation.start();

  moveAliens = function(x, y) {
    return _.each(aliensArr, function(alien) {
      return alien.move(x, y);
    });
  };

  removeAlien = function(alien) {
    var index;

    if (alien) {
      index = aliensArr.indexOf(alien);
      alien.destroy();
      return aliensArr.splice(index, 1);
    }
  };

  checkAliensGoDown = function() {
    _.each(aliensArr, function(alien) {
      if (aliensDirection < 0 && alien.getX() - aliensSideMove < 0) {
        return true;
      } else if (aliensDirection > 0 && alien.getX() + aliensSideMove > WIDTH - 12 * BLOCK_SIZE) {
        return true;
      }
    });
    return false;
  };

  animateAliens = function() {
    var direction;

    if (checkAliensGoDown()) {
      direction = -1 * aliensDirection;
      return moveAliens(0, aliensDownMove);
    } else {
      return moveAliens(aliensSideMove * direction, 0);
    }
  };

  setInterval(animateAliens, alienMovPause);

}).call(this);
