// Generated by CoffeeScript 1.6.2
(function() {
  var HEIGHT, WIDTH, angle_to_vector, distance, lives, rot_speed, score, time;

  WIDTH = 800;

  HEIGHT = 600;

  score = 0;

  lives = 3;

  time = 0;

  rot_speed = 0.1;

  angle_to_vector = function(angle) {
    return [Math.cos(angle), Math.sin(angle)];
  };

  distance = function(initial, final) {
    var diffx, diffy;

    diffx = initial[0] - final[0];
    diffy = initial[1] - final[1];
    return Math.sqrt(diffx * diffx + diffy * diffy);
  };

  window.onload = function() {
    var layer, rect, stage;

    stage = new Kinetic.Stage({
      container: 'container',
      width: 328,
      height: 200
    });
    console.log(stage);
    layer = new Kinetic.Layer();
    rect = new Kinetic.Rect({
      x: 239,
      y: 75,
      width: 100,
      height: 50,
      fill: 'green',
      stroke: 'black',
      strokeWidth: 4
    });
    layer.add(rect);
    return stage.add(layer);
  };

}).call(this);
