// Generated by CoffeeScript 1.4.0
(function() {

  window.Game = {};

  Game.Main = (function() {

    function Main(width, height) {
      this.width = width;
      this.height = height;
      this.stage = new Kinetic.Stage({
        container: 'container',
        width: this.width,
        height: this.height
      });
      this.layers = [];
      this.ships = [];
    }

    Main.prototype.createBackground = function() {
      this.layers.push(new Kinetic.Layer);
      return this.layers[this.layers.length - 1].add(new Kinetic.Rect({
        x: 0,
        y: 0,
        width: this.width,
        height: this.height,
        fill: "#000000"
      }));
    };

    Main.prototype.createStars = function(number) {
      var n, starsGroup, _i;
      this.layers.push(new Kinetic.Layer);
      starsGroup = new Kinetic.Group;
      for (n = _i = 0; 0 <= number ? _i <= number : _i >= number; n = 0 <= number ? ++_i : --_i) {
        starsGroup.add(new Kinetic.Star({
          x: Math.random() * this.width,
          y: Math.random() * this.height,
          numPoints: 5,
          innerRadius: Math.random() + 0.5,
          outerRadius: Math.random() * 2 + 1.5,
          fill: "#FFFFAA"
        }));
      }
      return this.layers[this.layers.length - 1].add(starsGroup);
    };

    Main.prototype.addShip = function(x, y) {
      this.layers.push(new Kinetic.Layer);
      this.ships.push(new Game.Ship(x, y));
      return this.layers[this.layers.length - 1].add(this.ships[this.ships.length - 1].ship);
    };

    Main.prototype.start = function() {
      var layer, _i, _len, _ref, _results;
      _ref = this.layers;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        layer = _ref[_i];
        _results.push(this.stage.add(layer));
      }
      return _results;
    };

    return Main;

  })();

}).call(this);
