// Generated by CoffeeScript 1.4.0
(function() {

  window.Game = {};

  Game.Main = (function() {

    function Main(width, height) {
      this.width = width;
      this.height = height;
      this.stage = new Kinetic.Stage({
        container: 'container',
        width: this.width,
        height: this.height
      });
      this.backgroundLayer = new Kinetic.Layer;
      this.starsLayer = new Kinetic.Layer;
      this.shipLayer = new Kinetic.Layer;
      this.ship1 = null;
    }

    Main.prototype.createBackground = function() {
      return this.backgroundLayer.add(new Kinetic.Rect({
        x: 0,
        y: 0,
        width: this.width,
        height: this.height,
        fill: "#000000"
      }));
    };

    Main.prototype.createStars = function(number) {
      var n, starsGroup, _i;
      starsGroup = new Kinetic.Group;
      for (n = _i = 0; 0 <= number ? _i <= number : _i >= number; n = 0 <= number ? ++_i : --_i) {
        starsGroup.add(new Kinetic.Star({
          x: Math.random() * this.width,
          y: Math.random() * this.height,
          numPoints: 5,
          innerRadius: Math.random() + 0.5,
          outerRadius: Math.random() * 2 + 1.5,
          fill: "#FFFFAA"
        }));
      }
      return this.starsLayer.add(starsGroup);
    };

    Main.prototype.addShip = function(x, y) {
      this.ship1 = new Game.Ship(x, y);
      this.shipLayer.add(this.ship1.ship);
      return this.ship1;
    };

    Main.prototype.start = function() {
      this.stage.add(this.backgroundLayer);
      this.stage.add(this.starsLayer);
      return this.stage.add(this.shipLayer);
    };

    return Main;

  })();

}).call(this);
