// Generated by CoffeeScript 1.4.0
(function() {
  var HEIGHT, NUM_STARS, WIDTH, game;

  WIDTH = 800;

  HEIGHT = 600;

  NUM_STARS = 200;

  game = new Game.Main(WIDTH, HEIGHT);

  game.createBackground();

  game.createStars(NUM_STARS);

  game.addShip(WIDTH / 2, HEIGHT / 2);

  game.start();

}).call(this);
