// Generated by CoffeeScript 1.4.0
(function() {
  var HEIGHT, NUM_STARS, WIDTH, game, ship;

  WIDTH = 800;

  HEIGHT = 600;

  NUM_STARS = 200;

  game = new Game.Main(WIDTH, HEIGHT);

  game.createBackground();

  game.createStars(NUM_STARS);

  ship = game.addShip(WIDTH / 2, HEIGHT / 2);

  window.$(document).ready(function() {
    var shipAnim;
    window.$(document).keydown(function(e) {
      switch (e.keyCode) {
        case 37:
        case 65:
          ship.setRotation(-10);
          break;
        case 38:
        case 87:
          ship.setAcceleration(.5);
          break;
        case 39:
        case 68:
          ship.setRotation(10);
      }
      return e.preventDefault();
    });
    game.start();
    shipAnim = new Kinetic.Animation(function(frame) {
      if (game.ship1) {
        game.ship1.rotate(frame, game.ship1.rotation);
        game.ship1.moveShip();
        console.log(game.ship1.ship.getPosition());
      }
      return game.shipLayer;
    });
    return shipAnim.start();
  });

}).call(this);
