// Generated by CoffeeScript 1.6.2
(function() {
  Game.Rock = (function() {
    function Rock(x, y, imageObj) {
      var animations;

      this.x = x;
      this.y = y;
      this.imageObj = imageObj;
      animations = {
        idle: [
          {
            x: 0,
            y: 0,
            width: 90,
            height: 90
          }
        ]
      };
      this.rock_obj = new Kinetic.Sprite({
        x: this.x,
        y: this.y,
        image: imageObj,
        animation: animations,
        frameRate: 7,
        index: 0
      });
      this.rock_obj.setOffset(45, 45);
      this.velocity = {
        x: 0,
        y: 0
      };
      this.acceleration = 0;
      this.rotation = 0;
    }

    Rock.prototype.moveRock = function() {
      return this.rock_obj.move(Math.cos(this.rock_obj.getRotation()) * Game.ROCK_SPEED, Math.sin(this.rock_obj.getRotation()) * Game.ROCK_SPEED);
    };

    return Rock;

  })();

}).call(this);
