// Generated by CoffeeScript 1.4.0
(function() {
  var DRAG, HEIGHT, MAX_SPEED, WIDTH, adjustScreenPosition, backgroundLayer, createStars, hypotenuse, moveShip, rotateShip, setShipAcceleration, ship, shipAnimation, shipLayer, ship_acceleration, ship_velocity, stage, starsGroup, starsLayer;

  WIDTH = window.innerWidth;

  HEIGHT = window.innerHeight;

  MAX_SPEED = 4;

  DRAG = 0.01;

  ship = null;

  stage = new Kinetic.Stage({
    container: 'container',
    width: WIDTH,
    height: HEIGHT
  });

  backgroundLayer = new Kinetic.Layer;

  backgroundLayer.add(new Kinetic.Rect({
    x: 0,
    y: 0,
    width: WIDTH,
    height: HEIGHT,
    fill: "#000000"
  }));

  starsLayer = new Kinetic.Layer;

  starsGroup = new Kinetic.Group;

  createStars = function(num) {
    var n, _i, _results;
    _results = [];
    for (n = _i = 0; 0 <= num ? _i <= num : _i >= num; n = 0 <= num ? ++_i : --_i) {
      _results.push(starsGroup.add(new Kinetic.Star({
        x: Math.random() * WIDTH,
        y: Math.random() * HEIGHT,
        numPoints: 5,
        innerRadius: Math.random() * 1 + 0.5,
        outerRadius: Math.random() * 2 + 1.5,
        fill: '#FFFFAA'
      })));
    }
    return _results;
  };

  createStars(200);

  starsLayer.add(starsGroup);

  shipLayer = new Kinetic.Layer;

  ship = new Kinetic.Polygon({
    points: [-15, -10, 15, 0, -15, 10],
    sides: 3,
    radius: 10,
    fill: "#42B4E6"
  });

  ship.setPosition(WIDTH / 2, HEIGHT / 2);

  ship.setRotation(-Math.PI / 2);

  ship_velocity = {
    x: 0,
    y: 0
  };

  ship_acceleration = 0;

  shipLayer.add(ship);

  shipAnimation = new Kinetic.Animation(function(frame) {
    if (ship) {
      document.onkeydown = function(event) {
        switch (event.keyCode) {
          case 37:
          case 65:
            return rotateShip(frame, -2);
          case 38:
          case 87:
            console.log('up');
            return setShipAcceleration(1);
          case 39:
          case 68:
            return rotateShip(frame, 2);
          case 40:
          case 83:
            return console.log('down');
          case 32:
            return console.log('pew');
        }
      };
      return moveShip();
    }
  }, shipLayer);

  moveShip = function() {
    var movementAngle, speed, speedAngle;
    if (ship_acceleration !== 0) {
      movementAngle = ship.getRotation();
      ship_velocity.x += Math.cos(movementAngle) * ship_acceleration;
      ship_velocity.y += Math.sin(movementAngle) * ship_acceleration;
      ship_acceleration = 0;
    }
    speed = hypotenuse(ship_velocity.x, ship_velocity.y);
    if (speed > MAX_SPEED) {
      speed = MAX_SPEED;
    } else if (speed > 0.1) {
      speed -= DRAG;
    }
    speedAngle = Math.atan2(ship_velocity.y, ship_velocity.x);
    ship_velocity.x = Math.cos(speedAngle) * speed;
    ship_velocity.y = Math.sin(speedAngle) * speed;
    ship.move(ship_velocity.x, ship_velocity.y);
    return adjustScreenPosition(ship, WIDTH, HEIGHT);
  };

  setShipAcceleration = function(accel) {
    return ship_acceleration += accel;
  };

  hypotenuse = function(x, y) {
    return Math.sqrt(x * x + y * y);
  };

  adjustScreenPosition = function(shape, width, height) {
    if (shape.getX() >= width) {
      shape.setX(0);
    } else if (shape.getX() < 0) {
      shape.setX(width);
    }
    if (shape.getY() >= height) {
      return shape.setY(0);
    } else if (shape.getY() < 0) {
      return shape.setY(height);
    }
  };

  shipAnimation.start();

  rotateShip = function(frame, dir) {
    var angleDiff, angularSpeed;
    angularSpeed = Math.PI / 2;
    angleDiff = frame.timeDiff * angularSpeed / 1000;
    return ship.rotate(dir * angleDiff);
  };

  stage.add(backgroundLayer);

  stage.add(starsLayer);

  stage.add(shipLayer);

}).call(this);
