// Generated by CoffeeScript 1.4.0
(function() {
  var DRAG, HEIGHT, MAX_SPEED, WIDTH, createStars, rotateShip, ship, shipAnimation, shipLayer, stage, starsGroup, starsLayer;

  WIDTH = window.innerWidth;

  HEIGHT = window.innerHeight;

  MAX_SPEED = 5;

  DRAG = 0.01;

  ship = null;

  stage = new Kinetic.Stage({
    container: 'container',
    width: WIDTH,
    height: HEIGHT
  });

  starsLayer = new Kinetic.Layer;

  starsGroup = new Kinetic.Group;

  createStars = function(num) {
    var n, _i, _results;
    _results = [];
    for (n = _i = 0; 0 <= num ? _i <= num : _i >= num; n = 0 <= num ? ++_i : --_i) {
      _results.push(starsGroup.add(new Kinetic.Star({
        x: Math.random() * WIDTH,
        y: Math.random() * HEIGHT,
        numPoints: 5,
        innerRadius: Math.random() * 1 + 0.5,
        outerRadius: Math.random() * 2 + 1.5,
        fill: '#FFFFAA'
      })));
    }
    return _results;
  };

  createStars(200);

  starsLayer.add(starsGroup);

  shipLayer = new Kinetic.Layer;

  ship = new Kinetic.Polygon({
    points: [10, 0, 20, 30, 0, 30],
    sides: 3,
    radius: 10,
    fill: "#42B4E6"
  });

  ship.setPosition(WIDTH / 2, HEIGHT / 2);

  shipLayer.add(ship);

  shipAnimation = new Kinetic.Animation(function(frame) {
    if (ship) {
      return document.onkeydown = function(event) {
        switch (event.keyCode) {
          case 37:
          case 65:
            return rotateShip(frame, -1);
          case 38:
          case 87:
            console.log('up');
            return ship.move(1, 0);
          case 39:
          case 68:
            return rotateShip(frame, 1);
          case 40:
          case 83:
            return console.log('down');
          case 32:
            return console.log('pew');
        }
      };
    }
  }, shipLayer);

  shipAnimation.start();

  rotateShip = function(frame, dir) {
    var angleDiff, angularSpeed;
    angularSpeed = Math.PI / 2;
    angleDiff = frame.timeDiff * angularSpeed / 1000;
    return ship.rotate(dir * angleDiff);
  };

  stage.add(starsLayer);

  stage.add(shipLayer);

}).call(this);
