// Generated by CoffeeScript 1.4.0
(function() {
  var Asteroids, DRAG, MAX_SPEED, SCREEN_HEIGHT, SCREEN_WIDTH, Ship, asteroids;

  SCREEN_WIDTH = window.innerWidth;

  SCREEN_HEIGHT = window.innerHeight;

  MAX_SPEED = 5;

  DRAG = 0.01;

  asteroids = new Asteroids();

  asteroids.start();

  Asteroids = (function() {

    function Asteroids() {
      var ship;
      this.stage = new Kinetic.Stage({
        container: 'container',
        width: SCREEN_WIDTH,
        height: SCREEN_HEIGHT
      });
      this.backgroundLayer = new Kinetic.Layer();
      this.backgroundLayer.add(new Kinetic.Rect({
        width: SCREEN_WIDTH,
        height: SCREEN_HEIGHT,
        fill: '#000000'
      }));
      this.shipLayer = new Kinetic.Layer();
      ship = new Ship();
      this.shipLayer.add(ship.shape);
      this.stage.add(this.backgroundLayer);
      this.stage.add(this.shipLayer);
    }

    Asteroids.prototype.start = function() {
      return this.stage.start();
    };

    return Asteroids;

  })();

  Ship = (function() {

    function Ship() {
      this.shape = new Kinetic.Polygon({
        points: [10, 0, 20, 30, 0, 30],
        sides: 3,
        radius: 10,
        fill: "#42B4E6"
      });
      this.position = {
        x: this.shape.getX(),
        y: this.shape.getY()
      };
      this.velocity = {
        x: 0,
        y: 0
      };
      this.acceleration = 0;
      this.rotation = 0;
      this.bullets = [];
    }

    return Ship;

  })();

}).call(this);
