// Generated by CoffeeScript 1.6.2
(function() {
  window.describe("Game class", function() {
    var game;

    game = null;
    beforeEach(function() {
      return game = new Game.Main(0, 0);
    });
    it("should be different from null", function() {
      return expect(game).not.toEqual(null);
    });
    describe("Constructor default values", function() {
      it("should have width 0", function() {
        return expect(game.width).toEqual(0);
      });
      it("should have height 0", function() {
        return expect(game.height).toEqual(0);
      });
      it("should have a new stage", function() {
        return expect(game.stage).toBeDefined();
      });
      it("should have the stage's width 0", function() {
        return expect(game.stage.getWidth()).toEqual(0);
      });
      it("should have the stage's height 0", function() {
        return expect(game.stage.getHeight()).toEqual(0);
      });
      return it("should have layers", function() {
        return expect(game.layers).toBeDefined();
      });
    });
    describe("Creating the background", function() {
      beforeEach(function() {
        return game.createBackground();
      });
      it("should have a game instance", function() {
        return expect(game).toBeDefined();
      });
      it("should have a new layer", function() {
        return expect(game.layers.length).toBeGreaterThan(0);
      });
      return it("should have a rect defined inside the layer", function() {
        return expect(game.layers[game.layers.length - 1]).toBeDefined();
      });
    });
    return describe("Creating Stars", function() {
      beforeEach(function() {
        return game.createStars(10);
      });
      return it("should create a new layer", function() {
        return expect(game.layers.length).toBeGreaterThan(0);
      });
    });
  });

}).call(this);
