// Generated by CoffeeScript 1.4.0
(function() {

  window.describe("Ship class", function() {
    var ship;
    ship = null;
    beforeEach(function() {
      return ship = new Game.Ship(0, 0);
    });
    it("should be different from null", function() {
      return expect(ship).not.toEqual(null);
    });
    describe("Constructor default values", function() {
      it("should have max_speed 4", function() {
        return expect(ship.max_speed).toEqual(4);
      });
      it("should have drag 0.01", function() {
        return expect(ship.drag).toEqual(0.01);
      });
      it("should have a ship instance", function() {
        return expect(ship.ship).toBeDefined();
      });
      it("should have zero velocity", function() {
        expect(ship.velocity.x).toEqual(0);
        return expect(ship.velocity.y).toEqual(0);
      });
      it("should have zero acceleration", function() {
        return expect(ship.acceleration).toEqual(0);
      });
      return it("should be in position 0 0", function() {
        expect(ship.x).toEqual(0);
        return expect(ship.y).toEqual(0);
      });
    });
    describe("Set a new position", function() {
      beforeEach(function() {
        return ship.setPosition(3, 5);
      });
      return it("should have a new position 3, 5", function() {
        expect(ship.x).toEqual(3);
        return expect(ship.y).toEqual(5);
      });
    });
    describe("Set a new acceleration", function() {
      beforeEach(function() {
        return ship.setAcceleration(2);
      });
      return it("should have new acceleration equal to 2", function() {
        return expect(ship.acceleration).toEqual(2);
      });
    });
    return describe("Get Hypotenuse value", function() {
      return it("the hypotenuse of 3 and 4 should be 5", function() {
        var hypotenuse;
        hypotenuse = ship.getHypotenuse(3, 4);
        return expect(hypotenuse).toEqual(5);
      });
    });
  });

}).call(this);
