// Generated by CoffeeScript 1.4.0
(function() {
  var Alien, AliensGroup, BLOCK_SIZE, Canon, HEIGHT, HEIGHT_BLOCKS, SpriteImage, WIDTH, WIDTH_BLOCKS, aliensArr, aliensGroup, animation, animations, background, canon, canonSpeed, imageObj, layer, movCount, movDirection, movDownDist, movSideDist, stage, startTime;

  BLOCK_SIZE = 3;

  WIDTH_BLOCKS = 184;

  HEIGHT_BLOCKS = 191;

  WIDTH = WIDTH_BLOCKS * BLOCK_SIZE;

  HEIGHT = HEIGHT_BLOCKS * BLOCK_SIZE;

  aliensArr = [];

  canon = null;

  startTime = 0;

  movCount = 0;

  movDirection = 1;

  movSideDist = 2 * BLOCK_SIZE;

  movDownDist = 6 * BLOCK_SIZE;

  canonSpeed = 15;

  stage = new Kinetic.Stage({
    container: "container",
    width: WIDTH,
    height: HEIGHT
  });

  layer = new Kinetic.Layer();

  background = new Kinetic.Rect({
    x: 0,
    y: 0,
    width: WIDTH,
    height: HEIGHT,
    fill: "#000000"
  });

  layer.add(background);

  animations = {
    alien01: [
      {
        x: BLOCK_SIZE,
        y: BLOCK_SIZE,
        width: 12 * BLOCK_SIZE,
        height: 8 * BLOCK_SIZE
      }, {
        x: 14 * BLOCK_SIZE,
        y: BLOCK_SIZE,
        width: 12 * BLOCK_SIZE,
        height: 8 * BLOCK_SIZE
      }
    ],
    alien02: [
      {
        x: BLOCK_SIZE,
        y: 10 * BLOCK_SIZE,
        width: 11 * BLOCK_SIZE,
        height: 8 * BLOCK_SIZE
      }, {
        x: 13 * BLOCK_SIZE,
        y: 10 * BLOCK_SIZE,
        width: 11 * BLOCK_SIZE,
        height: 8 * BLOCK_SIZE
      }
    ],
    alien03: [
      {
        x: BLOCK_SIZE,
        y: 19 * BLOCK_SIZE,
        width: 8 * BLOCK_SIZE,
        height: 8 * BLOCK_SIZE
      }, {
        x: 10 * BLOCK_SIZE,
        y: 19 * BLOCK_SIZE,
        width: 8 * BLOCK_SIZE,
        height: 8 * BLOCK_SIZE
      }
    ],
    spaceship: [
      {
        x: BLOCK_SIZE,
        y: (3 * 8 + 4) * BLOCK_SIZE,
        width: 16 * BLOCK_SIZE,
        height: 8 * BLOCK_SIZE
      }
    ],
    canon: [
      {
        x: BLOCK_SIZE,
        y: (4 * 8 + 5) * BLOCK_SIZE,
        width: 15 * BLOCK_SIZE,
        height: 8 * BLOCK_SIZE
      }
    ],
    hidden: [
      {
        x: 0,
        y: 0,
        width: 0,
        height: 0
      }
    ]
  };

  imageObj = new Image();

  aliensGroup = new Kinetic.Group();

  imageObj.onload = function() {
    var alien, num1, num2, _i, _j, _k, _len;
    canon = new Canon();
    layer.add(canon.kinetic_sprite);
    for (num1 = _i = 0; _i <= 4; num1 = ++_i) {
      for (num2 = _j = 0; _j <= 10; num2 = ++_j) {
        if (num1 === 0) {
          aliensArr.push(new Alien(BLOCK_SIZE + num2 * (12 + 2) * BLOCK_SIZE, num1 * (8 + 6) * BLOCK_SIZE, 'alien03'));
        }
        if (num1 === 1 || num1 === 2) {
          aliensArr.push(new Alien(num2 * (12 + 2) * BLOCK_SIZE, num1 * (8 + 6) * BLOCK_SIZE, 'alien02'));
        }
        if (num1 === 3 || num1 === 4) {
          aliensArr.push(new Alien(num2 * (12 + 2) * BLOCK_SIZE, num1 * (8 + 6) * BLOCK_SIZE, 'alien01'));
        }
      }
    }
    for (_k = 0, _len = aliensArr.length; _k < _len; _k++) {
      alien = aliensArr[_k];
      aliensGroup.add(alien.kinetic_sprite);
      layer.add(aliensGroup);
      alien.kinetic_sprite.attrs.frameRate = 2;
      alien.kinetic_sprite.start();
    }
    aliensGroup.move(BLOCK_SIZE, BLOCK_SIZE);
    document.onkeydown = function(event) {
      switch (event.keyCode) {
        case 37:
        case 65:
          return canon.startMove(-canonSpeed);
        case 39:
        case 68:
          return canon.startMove(canonSpeed);
        case 32:
          return canon.shoot();
      }
    };
    return document.onkeyup = function(event) {
      return canon.stopMove();
    };
  };

  stage.add(layer);

  animation = new Kinetic.Animation(function(frame) {
    if (canon) {
      canon.move();
    }
    if (frame.time - startTime > 500) {
      startTime = frame.time;
      if (movCount % 16 === 15) {
        aliensGroup.move(0, movDownDist);
        movDirection *= -1;
      } else {
        aliensGroup.move(movDirection * movSideDist, 0);
      }
      return movCount++;
    }
  });

  animation.start();

  imageObj.src = "img/aliens_all.png";

  AliensGroup = (function() {

    function AliensGroup() {
      this.aliensGroup = new Kinetic.Group();
      this.aliensArr = [];
    }

    AliensGroup.prototype.initialize = function() {
      var alien, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = aliensArr.length; _i < _len; _i++) {
        alien = aliensArr[_i];
        this.aliensGroup.add(alien.kinetic_sprite);
        layer.add(aliensGroup);
        _results.push(alien.kinetic_sprite.start());
      }
      return _results;
    };

    return AliensGroup;

  })();

  /*
  # TODO: redo basic sprite class to be extended (constructor, move, detect shoot, etc)
  */


  SpriteImage = (function() {

    function SpriteImage(x, y, image, animation, animations, frameRate) {
      this.x = x;
      this.y = y;
      this.image = image;
      this.animation = animation;
      this.animations = animations;
      this.frameRate = frameRate;
      this.alive = true;
      this.kinetic_sprite = new Kinetic.Sprite({
        x: this.x,
        y: this.y,
        image: this.image,
        animation: this.animation,
        animations: this.animations,
        frameRate: this.frameRate
      });
    }

    SpriteImage.prototype.setWidth = function(width) {
      return this.kinetic_sprite.setWidth(width);
    };

    SpriteImage.prototype.setHeight = function(height) {
      return this.kinetic_sprite.setHeight(height);
    };

    SpriteImage.prototype.getWidth = function() {
      return this.kinetic_sprite.getWidth();
    };

    SpriteImage.prototype.getHeight = function() {
      return this.kinetic_sprite.getHeight();
    };

    SpriteImage.prototype.kill = function() {
      this.alive = false;
      return this.kinetic_sprite.setAnimation('hidden');
    };

    SpriteImage.prototype.isAlive = function() {
      return this.alive;
    };

    return SpriteImage;

  })();

  Alien = (function() {

    function Alien(x, y, animation) {
      this.x = x;
      this.y = y;
      this.animation = animation;
      this.alive = true;
      this.kinetic_sprite = new Kinetic.Sprite({
        x: this.x,
        y: this.y,
        image: imageObj,
        animation: this.animation,
        animations: animations,
        frameRate: 2
      });
      this.kinetic_sprite.setHeight(8 * BLOCK_SIZE);
      switch (this.animation) {
        case 'alien01':
          this.kinetic_sprite.setWidth(8 * BLOCK_SIZE);
          break;
        case 'alien02':
          this.kinetic_sprite.setWidth(11 * BLOCK_SIZE);
          break;
        case 'alien03':
          this.kinetic_sprite.setWidth(12 * BLOCK_SIZE);
      }
    }

    Alien.prototype.kill = function() {
      this.alive = false;
      return this.kinetic_sprite.setAnimation('hidden');
    };

    Alien.prototype.isAlive = function() {
      return this.alive;
    };

    Alien.prototype.setFrameRate = function(framerate) {
      this.framerate = framerate;
      this.kinetic_sprite.attrs.frameRate = this.framerate;
      return this.kinetic_sprite.start();
    };

    return Alien;

  })();

  Canon = (function() {

    function Canon() {
      this.speed = 0;
      this.kinetic_sprite = new Kinetic.Sprite({
        x: WIDTH / 2 - 7 * BLOCK_SIZE,
        y: HEIGHT - 8 * BLOCK_SIZE,
        image: imageObj,
        animation: 'canon',
        animations: animations,
        frameRate: 1
      });
      this.kinetic_sprite.setWidth(15 * BLOCK_SIZE);
      this.kinetic_sprite.setHeight(8 * BLOCK_SIZE);
    }

    Canon.prototype.startMove = function(vel) {
      return this.speed = vel;
    };

    Canon.prototype.stopMove = function() {
      return this.speed = 0;
    };

    Canon.prototype.shoot = function() {
      return console.log("pew!");
    };

    Canon.prototype.move = function() {
      var sprite, vel, x;
      vel = this.speed;
      sprite = this.kinetic_sprite;
      x = sprite.getX();
      if ((vel < 0 && x > 0) || (vel > 0 && x < WIDTH - 15 * BLOCK_SIZE)) {
        return sprite.move(vel, 0);
      }
    };

    return Canon;

  })();

}).call(this);
